### ISSUE TITLE
New HiPS JSON URL

### ISSUE THREAD

**Issue by astrodavid10** [WorldWideTelescope/wwt-hips-list-importer#3]
Looks like the HiPS URL at line 327 is no longer a viable URL - I dug a bit, but didn't find an ideal way to query CDS.

**Comment by imbasimba** [comment]
@tboch @bmatthieu3 Is [https://aladin.u-strasbg.fr/hips/globalhipslist](https://aladin.u-strasbg.fr/hips/globalhipslist) dead forever, or is it just something temporary?

**Comment by tboch** [comment]
@astrodavid10 @imbasimba : thanks for pointing this out. Gonna investigate why this is no more working

**Comment by tboch** [comment]
@astrodavid10 @imbasimba should be fixed now.
Let me know if you still have issues.

**Comment by imbasimba** [comment]
Thanks @tboch!

**Comment by astrodavid10** [comment]
@tboch Thanks!
